### ISSUE TITLE
Weird scroll behavior when using `scrollToIndex` with `react-select`

### ISSUE THREAD

**Issue by mahaveer0496** [tannerlinsley/react-virtual#100]
I'm using this library to virtualize `react-select`'s `menuList` and when using `scrollToIndex` after the menu opens, the scroll gets stuck sometimes.

Step to reproduce - 
1. Open [this codesandbox](https://codesandbox.io/s/virtual-select-31jym?file=/src/App.js) 
2. Click menu
2. Select last element -> Click menu again
3. Try to scroll

Thanks in advance!

**Comment by tannerlinsley** [comment]
The `MenuList` component you are using is the culprit I believe. Turning it into a div, everything is fixed. My guess is that it's either not rendering it's styles the way you expect, or its trapping scroll events or something. I would file an issue with react-select.
