### ISSUE TITLE
`measureRef` is new different every render, causing rows to be rerendered unnecessarily on scroll

### ISSUE THREAD

**Issue by gausie** [tannerlinsley/react-virtual#108]
I'm trying to memoize the contents of my rows but the `measureRef` prop that gets passed is unique every time virtualItems is created.

**Comment by colesimmons** [comment]
Same here

**Comment by tannerlinsley** [comment]
I think I get what you're asking, but I'll need you to resubmit the issue with a codesandbox so we can debug *exactly* what you're referring to (we run a strict policy on reproduction for issues)
