### ISSUE TITLE
How to use infinite scroll on top of page

### ISSUE THREAD

**Issue by ESTAID** [tannerlinsley/react-virtual#109]
I'm wondering about way to  infinite scroll on top of page.
I tried using the totalSize value but it failed.

**Comment by tannerlinsley** [comment]
I'm not quite sure what you're asking. If it's an issue, please open a new one with a codesandbox, otherwise feel free to ask your question as a discussion or in the [TanStack.com discord channel](https://tlinz.com/discord)
