### ISSUE TITLE
Re-measure on height change

### ISSUE THREAD

**Issue by danielr18** [tannerlinsley/react-virtual#11]
Hi @tannerlinsley, is there a way to re-measure a row height when it changes? I have a virtualized list with truncated descriptions that can be expanded, and I tried to recreate a similar use case in the sandbox and it seems the only way to remeasure would be either scrolling or change `estimateSize` memoization.

Here's the example, when you click one of the rows, its height change and they start to overlap. 
![May-09-2020 10-33-34](https://user-images.githubusercontent.com/9046616/81476600-babef500-91e0-11ea-8f9b-9a4b5a1e3cbc.gif)

**Comment by tannerlinsley** [comment]
Does changing the estimator memo not work?

**Comment by danielr18** [comment]
It does work

**Comment by tannerlinsley** [comment]
For now it is. If it becomes a pain and you’d rather have a function like virtualizer.measure() we can discuss that later.

**Comment by patygonsalves** [comment]
I have the same problem

**Comment by ItaiPendler** [comment]
> Does changing the estimator memo not work?

Could you please elaborate what that means? 
Is there a reference in the docs that explains this?
