### ISSUE TITLE
Why this library isn't written in Typescript?

### ISSUE THREAD

**Issue by enesTufekci** [tannerlinsley/react-virtual#12]
Just kidding :) I am going to use this library but I need types, I can implement them or convert codebase to typescript if you want. What would be your preference? 

Cheers!

**Comment by tannerlinsley** [comment]
For now please feel free to implement the type defs in a PR. I’ll convert it to Typescript on my own later. 👍

**Comment by johnnyreilly** [comment]
Great to see this happening 🤗

When you make the TypeScript move it's worth taking https://github.com/jaredpalmer/tsdx for a spin. It'll make your life easier. Feel free to ping me if you would like assistance when it comes to TypeScript; I'd be happy to help!
