### ISSUE TITLE
Rendering dropdown menu inside react-virtual

### ISSUE THREAD

**Issue by martini97** [tannerlinsley/react-virtual#133]
Hey, I have a dropdown menu that uses an absolute position, however when rendering it inside the virtualized list the rows are not respecting the z-index, do you have any tips on how to fix it?

**Comment by tannerlinsley** [comment]
Because virtualized lists require an overflow, you'll need to use a portal to render your dropdown outside of the overflow context. There are lot of tooltip/popover/positioning libraries out there that support portals, so please look and see if yours does. If not, I would suggest using one that does :)

**Comment by jamesonhill** [comment]
Sorry to ping an old issue, but portals break keyboard accessibility. Is there still no way to render a dropdown / combobox within a virtualized row and maintain accessibility?

**Comment by piecyk** [comment]
@jamesonhill Not exactly, portals themselves don’t break accessibility, it’s usually the focus management that does. If you’re trying to render a dropdown/combobox inside a virtualized row, check out [FloatingFocusManager](https://floating-ui.com/docs/FloatingFocusManager?utm_source=chatgpt.com)
 from Floating UI. It works together with FloatingPortal to preserve tab order and handle focus/return focus correctly even when the popup is portaled outside the virtualized list. That way you can keep the dropdown accessible without fighting the virtualization unmounting issue.

**Comment by jamesonhill** [comment]
> @jamesonhill Not exactly, portals themselves don’t break accessibility, it’s usually the focus management that does. If you’re trying to render a dropdown/combobox inside a virtualized row, check out [FloatingFocusManager](https://floating-ui.com/docs/FloatingFocusManager?utm_source=chatgpt.com)
>  from Floating UI. It works together with FloatingPortal to preserve tab order and handle focus/return focus correctly even when the popup is portaled outside the virtualized list. That way you can keep the dropdown accessible without fighting the virtualization unmounting issue.

Yea fair point. I ended up handling focus myself but it was pretty tricky. Thanks for the recommendation.
