### ISSUE TITLE
Append to window scroll

### ISSUE THREAD

**Issue by Siemko** [tannerlinsley/react-virtual#14]
It is a pleasure writing an issue in such a great project!

I was wondering, if leaving the `height` and `width` properties on their own (https://codesandbox.io/s/empty-breeze-jzbry?file=/src/App.js:595-649) is the best option to make scrollable element of list snap to window scrollbar. It seems a little buggy. Do we have an option to make virtualized element snap its scrollbar to *main* browser scrollbar?

**Comment by tannerlinsley** [comment]
Hmm. I'm not sure exactly what you mean?

**Comment by Siemko** [comment]
Yeah, sorry if I complicated it a bit.

What I meant is to have virtualized list use `window` scrollbar. Will there be an option like that?

Right now setting parent element to 100% `width` and `height` makes scrolling cranky and virtualItmes are disappearing during scroll.

AFAIK, `react-virtualized` has component providing that, but an option to have it in headless hook would be great.

**Comment by tannerlinsley** [comment]
Can you pass parentRef: useRef(window)?

**Comment by Siemko** [comment]
It throws `element.getBoundingClientRect is not a function`.
https://codesandbox.io/s/dark-moon-21hkw

**Comment by tannerlinsley** [comment]
I see. Yeah window isn’t a dom node. Body tag is though!

**Comment by vpcvdc** [comment]
not happening properly @tannerlinsley 
[Sample code](https://codesandbox.io/s/new-http-yfe3t?file=/src/index.js)

**Comment by PierreAndreis** [comment]
@vpcvdc https://codesandbox.io/s/angry-jones-tswog?file=/src/index.js

**Comment by vpcvdc** [comment]
@PierreAndreis thank you for your response. But, your solution actually fully rendered all items.
wanna like "should only render items based on view-port size"

**Comment by vpcvdc** [comment]
My solution for true virtual concept in window scroll - [sample live code](https://codesandbox.io/s/busy-shape-qok2p?file=/src/index.js)

- window scroll (**without** virtual concept)
`
const parentRef = React.useRef(window.document.body);

  const rowVirtualizer = useVirtual({
    size: 10000,
    parentRef,
    estimateSize: React.useCallback(() => 35, []),
    overscan: 5
  });
`

- window scroll (**with** virtual concept)
`
const parentRef = React.useRef(window.document.body);

  const rowVirtualizer = useVirtual({
    size: 10000,
    parentRef,
    estimateSize: React.useCallback(() => 35, []),
    overscan: 5
  });

  const { scrollToOffset } = rowVirtualizer;
  React.useEffect(() => {
    const resizeHandler = () =>
      (window.document.body.style.height = `${window.innerHeight}px`);
    const scrollHandler = () => scrollToOffset(window.scrollY);
    window.addEventListener("resize", resizeHandler);
    window.addEventListener("scroll", scrollHandler, { passive: true });
    window.document.body.style.height = `${window.innerHeight}px`;
    scrollToOffset(window.scrollY);
    return () => {
      window.removeEventListener("resize", resizeHandler);
      window.removeEventListener("scroll", scrollHandler, { passive: true });
    };
  }, [scrollToOffset]);
`

@tannerlinsley Thank you for such a great library

**Comment by mogelbrod** [comment]
Using `body` as the parentRef unfortunately doesn't work as expected since it doesn't compensate for other content outside the virtualized list itself, which becomes more apparent when the virtual area doesn't take up most of the scroll container.

[**Example based off the code from @vpcvdc**](https://codesandbox.io/s/react-virtual-window-incorrect-ghcth?file=/src/index.js) - start scrolling to see that rows are being hidden before they go off screen.

I came up with the [following workaround](https://codesandbox.io/s/react-virtual-window-25kos?file=/src/index.js) to get the expected behaviour. Unfortunately it requires mocking/proxying the `parentRef` passed to the hook, which is bound to break if the hook internals change.

@tannerlinsley Can you (or anyone else for that matter) think of any other way to make this work without changes to the hook itself? If not it would be great to expose some mechanism to modify the scroll/bounding box calculations.

**Comment by petersendidit** [comment]
Looked in to how to better support using the window as the scroll element would look like. 

If `useVirtual` allowed passing in:
* `useRectFn` as a way to replace `useRect` so that different logic can be used based off of window 
* `onScrollElement` as a different element to bind the `onScroll` event on
* `scrollOffsetFn` to use different logic to decide the offset on scroll

Then it seems like it would be possible to have a wrapper that could leverage the existing logic.

```diff
diff --git a/src/index.js b/src/index.js
index f0c8337..b1a0144 100644
--- a/src/index.js
+++ b/src/index.js
@@ -1,10 +1,41 @@
 import React from 'react'
 
-import useRect from './useRect'
+import useRect, { useWindowRect } from './useRect'
 import useIsomorphicLayoutEffect from './useIsomorphicLayoutEffect'
 
 const defaultEstimateSize = () => 50
 
+export function useVirtualWindow({
+  windowObj,
+  scrollToFn,
+  horizontal,
+  parentRef,
+  ...rest
+}) {
+  const scrollKey = horizontal ? 'scrollX' : 'scrollY'
+  const defaultScrollToFn = React.useCallback(
+    offset => {
+      if (windowObj) {
+        window[scrollKey] = offset
+      }
+    },
+    [scrollKey, windowObj]
+  )
+
+  return useVirtual({
+    ...rest,
+    horizontal,
+    parentRef,
+    scrollToFn: defaultScrollToFn,
+    onScrollElement: windowObj,
+    scrollOffsetFn() {
+      const bounds = parentRef.current.getBoundingClientRect();
+      return horizontal ? bounds.left * -1 : bounds.top * -1;
+    },
+    useRectFn: (ref) => useWindowRect(windowObj, ref),
+  });
+}
+
 export function useVirtual({
   size = 0,
   estimateSize = defaultEstimateSize,
@@ -14,12 +45,15 @@ export function useVirtual({
   parentRef,
   horizontal,
   scrollToFn,
+  onScrollElement,
+  scrollOffsetFn,
+  useRectFn = useRect,
 }) {
   const sizeKey = horizontal ? 'width' : 'height'
   const scrollKey = horizontal ? 'scrollLeft' : 'scrollTop'
   const latestRef = React.useRef({})
 
-  const { [sizeKey]: outerSize } = useRect(parentRef) || {
+  const { [sizeKey]: outerSize } = useRectFn(parentRef) || {
     [sizeKey]: 0,
   }
 
@@ -68,10 +102,10 @@ export function useVirtual({
   const [range, setRange] = React.useState({ start: 0, end: 0 })
 
   useIsomorphicLayoutEffect(() => {
-    const element = parentRef.current
+    const element = onScrollElement || parentRef.current
 
     const onScroll = () => {
-      const scrollOffset = element[scrollKey]
+      const scrollOffset = scrollOffsetFn ? scrollOffsetFn() : element[scrollKey]
       latestRef.current.scrollOffset = scrollOffset
       setRange(prevRange => calculateRange(latestRef.current, prevRange))
     }
@@ -87,7 +121,7 @@ export function useVirtual({
     return () => {
       element.removeEventListener('scroll', onScroll)
     }
-  }, [parentRef.current, scrollKey, size /* required */])
+  }, [onScrollElement, parentRef.current, scrollKey, size /* required */])
 
   const virtualItems = React.useMemo(() => {
     const virtualItems = []
diff --git a/src/useRect.js b/src/useRect.js
index 1b67960..92a0a05 100644
--- a/src/useRect.js
+++ b/src/useRect.js
@@ -42,6 +42,36 @@ export default function useRect(nodeRef) {
   return rect
 }
 
+export function useWindowRect(windowObj, nodeRef) {
+  const [rect, dispatch] = React.useReducer(rectReducer, null)
+  useIsomorphicLayoutEffect(() => {
+    dispatch({
+      rect: {
+        height: windowObj.innerHeight,
+        width: windowObj.innerWidth,
+      }
+    });
+  }, [windowObj])
+
+  React.useEffect(() => {
+    const resizeHandler = () => {
+      dispatch({
+        rect: {
+          height: windowObj.innerHeight,
+          width: windowObj.innerWidth,
+        }
+      });
+    };
+    resizeHandler();
+    windowObj.addEventListener("resize", resizeHandler);
+    return () => {
+      windowObj.removeEventListener("resize", resizeHandler);
+    };
+  }, [nodeRef, windowObj]);
+
+  return rect
+}
+
 function rectReducer(state, action) {
   const rect = action.rect
   if (!state || state.height !== rect.height || state.width !== rect.width) {
```


The above code makes it so you can switch to using the window as the scroll element by doing: 

```jsx
  const rowVirtualizer = useVirtualWindow({
    size: 10000,
    parentRef,
    estimateSize: React.useCallback(() => 35, []),
    overscan: 5,
    windowObj: window,
  });
```

**Comment by mogelbrod** [comment]
I currently use this wrapping hook, compatible with the current release (v2.2.5):
```js
import React from 'react'
import { useVirtual } from 'react-virtual'

export function useVirtualWindow(options) {
  const sizeKey = options.horizontal ? 'width' : 'height'

  const virtualizedRef = options.parentRef
  const virtualizedBounds = React.useRef()

  const scrollListenerRef = React.useRef()
  // Mock the API surface currently used through parentRef
  const mockedParentRef = React.useRef({
    get scrollLeft() {
      return window.scrollX - virtualizedBounds.current.left
    },
    get scrollTop() {
      return window.scrollY - virtualizedBounds.current.top
    },
    getBoundingClientRect: () => ({
      width: window.innerWidth,
      height: window.innerHeight,
    }),
    addEventListener: (type, listener, ...args) => {
      // Only proxy 'scroll' event listeners
      if (type === 'scroll') {
        const proxiedListener = listener
        listener = scrollListenerRef.current = (originalEvent) => {
          // Some "scroll locking" implementations (such as for modals) work by
          // applying styling to the body. This optional offset will compensate
          // for that.
          const bodyOffset = parseInt(document.body.style.top || '0', 10)

          const target = {
            scrollLeft: window.scrollX - virtualizedBounds.current.left,
            scrollTop: window.scrollY - virtualizedBounds.current.top - bodyOffset,
          }
          proxiedListener({ target })
        }
        listener()
      }
      return document.addEventListener(type, listener, ...args)
    },
    removeEventListener: (type, listener, ...args) => {
      if (type === 'scroll') {
        listener = scrollListenerRef.current
      }
      return document.removeEventListener(type, listener, ...args)
    }
  })

  // Track dimensions of the virtualized container
  React.useLayoutEffect(() => {
    const onResize = () => {
      const rect = virtualizedRef.current.getBoundingClientRect()
      virtualizedBounds.current = {
        left: rect.left + window.scrollX,
        top: rect.top + window.scrollY,
      }
    }
    onResize()
    window.addEventListener('resize', onResize)
    return () => {
      window.removeEventListener('resize', onResize)
    }
  }, [virtualizedRef, sizeKey])

  return useVirtual({
    ...options,
    parentRef: mockedParentRef,
  })
}
```

As you can see it has to mock the parentRef to intercept bounds checking and the scroll event. Ideally some variation of the version provided by @petersendidit above would avoid these ugly hacks, while not messing with the API surface too much for the sake of a single use case.

**Comment by petersendidit** [comment]
I have opened #80 with the code that I posted above. Hopefully there is interest in officially supporting it.

**Comment by thanhlmm** [comment]
I can do it by using @mogelbrod comment.

Thank you so much
