### ISSUE TITLE
if measureRef is called multiple times with different values, scroll offset can be wrong

### ISSUE THREAD

**Issue by kalley** [tannerlinsley/react-virtual#152]
I attempted to put together a codesandbox for this (and will try again later), but we have a third-party component that can, on occasion, change it's height each re-render for ~3 cycles. This would normally be fine, except that it starts out relatively small, jumps up to something really big, then reverts to it's actual size. Internally, `react-virtual` keeps using the same `scrollOffset` because the `onScroll` handler does not get called for each change, which results in an inaccurate offset measurement. This can cause quite a jump while scrolling.

For now, I've just copied the code over and, in `defaultScrollToFn`, I also update `latestRef.current.scrollOffset` to equal what the `parentRef.current[scrollKey]` is being set to. This fixed my issue, but I don't know if it's the most effective way to deal with the mis-calculating.

**Comment by tannerlinsley** [comment]
I think this is a good workaround for now (and I hope it still is). I'm not sure how else to improve the situation currently, so let's keep tabs on this case and keep addressing it in the future as we improve the library.
