### ISSUE TITLE
Accessibility and keyboard navigation

### ISSUE THREAD

**Issue by jgoux** [tannerlinsley/react-virtual#158]
Hello all,

Is there anything that can be done to be able to scroll a virtualized list / table with the keyboard's arrows up/down?

If you focus an item and then try to maintain an arrow, it stops scrolling at some point and lose the focus. This issue doesn't seem to be present on react-virtualized.

**Comment by parkertomatoes** [comment]
I had a similar issue implementing keyboard controls. 

In my case, the issue was because the virtual rows had the `tabIndex={-1}` attribute set on them, so they focused when clicked on. The keyboard controls scrolled the list up and down without changing the focus, and the row lost focus as it moved outside of view and was removed.

I worked around this by removing `tabIndex` from the rows, and adding it to the list container. This way the entire list was focused instead of the individual rows.

**Comment by tannerlinsley** [comment]
I think @parkertomatoes is a good workaround for now. We're definitely looking for ways to improve the accessibility and keyboard-friendliness of the virtualizers in the future, so any suggestions are welcome.

**Comment by a2441918** [comment]
@parkertomatoes Can you provide a sample please?

**Comment by pavlovicIvan** [comment]
Any additional information would be useful, can anybody provide some samples for this workaround?

**Comment by flex-hyuntae** [comment]
How to use Virtual Scroll + Roving focus pattern

**Comment by flex-hyuntae** [comment]
I write like this

```
  const rowVirtualizer = useVirtualizer({
    count: items.length,
    getScrollElement: () => viewportRef?.current,
    estimateSize: () => LIST_ITEM_HEIGHT,
    getItemKey: index => index,
    onChange: e => {
      const virtualItems = e.getVirtualItems();
      const itemKeys = virtualItems.map(({ key }) => key);

      if (itemKeys.includes(Number(focusedItemIndex))) {
        return;
      }
      const firstItem = virtualItems[0];
      if (firstItem) {
        setFocusedItemIndex(`${firstItem.key}`);
      }
    },
  });
```

when change virtual items, check my focused element in virtual items key
and if not change focusedItemIndex

**Comment by tounsoo** [comment]
Why is this closed?

**Comment by piecyk** [comment]
@tounsoo It was closed because there are workarounds and patterns available that help implement this. If you’re running into this problem in a real use case, feel free to share a minimal example and we can point you to the most suitable approach.

**Comment by rburkovsky** [comment]
@piecyk can you take a look please?
https://codesandbox.io/p/sandbox/nice-bose-v59vpg

I am not sure what others desired behavior is, but mine is pretty simple: container must scroll up/down with arrow keys as focus moves through elements. Default MUI autocomplete behavior is just that, also included in the example for demonstration.

I removed `tabIndex` from list items as others have suggested, but it didn't make any difference. If I also add tabindex to container - there's no focus on elements at all and still nothing scrolls with arrow keys. Here you can see there's no tabindex on elements:

<img width="3047" height="1704" alt="Image" src="https://github.com/user-attachments/assets/f9c4949a-395c-4bad-b58d-36f6ddbe6e09" />
