### ISSUE TITLE
Dynamic row height

### ISSUE THREAD

**Issue by NadavShaar** [tannerlinsley/react-virtual#159]
How to set up a dynamic row height measured by `measureRef`? I know the `size` property should reflect the element's height but if I'm applying it to the row element, its height is always the estimated one, am i missing something?

```
<Row
    key={virtualRow.index}
    ref={el => measureRef(el)}
    style={{ transform: `translate3d(0, ${virtualRow.start}px, 0)`, height: `${virtualRow.size}px`}}
>
...
```

If i'm not setting up the height property on the row, Firefox crashes (seems like it's related to `setMeasuredCache`).

In all examples, the height of the rows is created randomly, what about setting the height by the row's content height?

**Comment by piecyk** [comment]
@NadavShaar in case of dynamic it will be set via measureRef, so no explicit height should be set on row.

> In all examples, the height of the rows is created randomly, what about setting the height by the row's content height?

Yeah, it's just to simplify the random height case, when looking on this example https://github.com/tannerlinsley/react-virtual/blob/master/examples/dynamic/src/index.js#L73-L80 we can omit the height from row, and push it to children to illustrate it better.

```jsx
<div
  key={virtualRow.index}
  ref={virtualRow.measureRef}
  className={virtualRow.index % 2 ? "ListItemOdd" : "ListItemEven"}
  style={{
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    transform: `translateY(${virtualRow.start}px)`
  }}
>
  <div style={{ height: `${rows[virtualRow.index]}px` }}>
    Row {virtualRow.index}
  </div>
</div>
```


Without codesandbox example hard to say why it crashes.

**Comment by NadavShaar** [comment]
Hi thanks for your reply...
https://codesandbox.io/s/youthful-wozniak-6k3g1?file=/src/index.js

Run this sandBox on firefox, for me the browser crushes.
Thanks.

**Comment by piecyk** [comment]
> Run this sandBox on firefox, for me the browser crashes,

Looks ok for me, running latest firefox.

<img width="1193" alt="Screenshot 2021-07-05 at 09 14 41" src="https://user-images.githubusercontent.com/82964/124432112-848fed80-dd71-11eb-8927-1d31132ec321.png">

Also here we see white space after row 9, because of the bug #112 cc @tannerlinsley ;)

**Comment by NadavShaar** [comment]
But did you tried to scroll? it happens only on scroll... BTW we have the exact same version of Firefox.
![Demo1](https://user-images.githubusercontent.com/8030614/124438569-05a2b100-dd81-11eb-9aa0-f5aed0033bef.gif)

**Comment by piecyk** [comment]
> But did you tried to scroll? it happens only on scroll...

Yes, scrolling also works as expected 🤔

**Comment by NadavShaar** [comment]
Shame... really liked this hook... thanks anyway.

**Comment by piecyk** [comment]
We can fix it, post stack trace and let's see why it throws.

**Comment by NadavShaar** [comment]
![Untitled](https://user-images.githubusercontent.com/8030614/124443479-641e5e00-dd86-11eb-952c-80897d91b7d9.png)
 Seems like an infinite loop related to `setMeasuredCache`

**Comment by piecyk** [comment]
@NadavShaar noticed that in codesandbox you are using `2.1.8` version, could you update to latest one and check again.

**Comment by NadavShaar** [comment]
Updated to 2.7.1 and the issue is still happening.

**Comment by piecyk** [comment]
Hmm this would mean that height from `getBoundingClientRect()` is different from cache value for each render. https://github.com/tannerlinsley/react-virtual/blob/master/src/index.js#L126

**Comment by piecyk** [comment]
We can log what was set to cache via `size` property on virtualItems

If you run this sandbox https://codesandbox.io/s/heuristic-nash-xvelv?file=/src/index.js what values you have in console before it throws?

**Comment by NadavShaar** [comment]
Chrome:

![chrome-capture (3)](https://user-images.githubusercontent.com/8030614/124456557-823e8b00-dd93-11eb-8210-0050b8733518.jpg)

Firefox:

![Untitled](https://user-images.githubusercontent.com/8030614/124456585-89fe2f80-dd93-11eb-87cf-06c7a405d977.png)

**Comment by piecyk** [comment]
Ok, my guess was right, also manage to reproduce it in firefox, using the browser zoom.

**Comment by NadavShaar** [comment]
Any idea what could cause these numbers? and why only Firefox?
Will removing the decimal from those values fix the issue?

**Comment by NadavShaar** [comment]
@piecyk I need to deliver the feature i'm working on in 2 days, should i expect a fix for this issue soon? otherwise, i won't be able to use this hook since i need to support Firefox too... ;-(

**Comment by piecyk** [comment]
@NadavShaar yep, i understand. One option is to use `offsetHeight, offsetWidth` rather than getBoundingClientRect when reading size. 

If we change, i'm wondering about correct position if the height is not an integer, so we have sub pixel rendering elements in list.

As it's pretty critical case for firefox, let's go with `offsetHeight, offsetWidth` for now.

**Comment by NadavShaar** [comment]
Played with it a little and i see it fixes the issue if i'm doing Math.floor to the measuredSize:
```
if (el) {
            const { [sizeKey]: measuredSize } = el.getBoundingClientRect();
            const roundedMeasuredSize = Math.floor(measuredSize);

            if (roundedMeasuredSize !== item.size) {
              if (item.start < scrollOffset) {
                defaultScrollToFn(scrollOffset + (roundedMeasuredSize - item.size));
              }

              setMeasuredCache(old => ({
                ...old,
                [keyExtractor(i)]: roundedMeasuredSize,
              }));
            }
          }
```

and also to size:
```

Can you test it?
const size = typeof measuredSize === 'number' ? Math.floor(measuredSize) : estimateSize(i);
```

**Comment by NadavShaar** [comment]
I can confirm Math.floor measuredSize and item.size fix the issue! i know it's not pretty but it's better than a broken app.

**Comment by piecyk** [comment]
> I can confirm Math.floor measuredSize and item.size fix the issue!

Yes, basic every rounding logic will fix it. One problem with it is when and to what value round it :) 

Maybe something like this https://github.com/tannerlinsley/react-virtual/pull/160 by adding `measureSize` prop user can decide how the rounding would be, and default will fallback to integers by `offsetWidth/offsetHeight`

**Comment by NadavShaar** [comment]
Great, please try to merge ASAP this is a major bug!
Thanks for the quick support... ;-)
