### ISSUE TITLE
Add totalItems in hook return value

### ISSUE THREAD

**Issue by gaetansnl** [tannerlinsley/react-virtual#162]
The `size` option we pass to the hook isn't always the one taken into account in the return value of the hook. A `totalItems` value could be returned to make code like this work more correctly 

```
    if(lastItem.index === virtualSize - 1 &&hasNextPage && !isFetching)
```
Here virtualSize passed to the hook `size` option is increased before useVirtual update the return value

![image](https://user-images.githubusercontent.com/8348807/125111001-a1b41b80-e0e5-11eb-99ea-1ec86cb084f4.png)

**Comment by piecyk** [comment]
> The size option we pass to the hook isn't always the one taken into account in the return value of the hook.

hmm size is not returned from hook, would keep it simple.

**Comment by gaetansnl** [comment]
Hello @piecyk. Thank you for your answer. I'm not sure to understand what you mean. The issue I try to describle is that the size we pass to the hook isn't equal to the size of the array returned even if all items should be displayed. You can see in the picture it takes multiple renders to update the virtualItems array to have 3 items. Maybe I'm missing something.

**Comment by piecyk** [comment]
> The issue I try to describle is that the size we pass to the hook isn't equal to the size of the array returned even if all items should be displayed. 

Yes, as it's returns an array of element's that fit's the viewport size + offset. My comment "keeping it simple" was about what we return from hook, question is if we really need to include the initial size we pass?

**Comment by tannerlinsley** [comment]
If it's an input that you want included, then I think it would be simple enough to just create a custom hook that adds it back into the return type for now. If it becomes cumbersome or difficult, we can investigate adding it in later.
