### ISSUE TITLE
Is `useVirtual().measure()` safe to use?

### ISSUE THREAD

**Issue by rzec-pki** [tannerlinsley/react-virtual#167]
I was having issues with rows not resizing properly when the height of the rows changed from some events (like resizing the browser) and one suggested solution I found in my investigation was to basically create a new `estimateSize` method. When I tried that, it kinda worked however I had two issues, it was delayed (content could briefly show up on top of each other) and sometimes on resizing, the list would not updating position properly.

I then noticed there was a `measure()` method on the object returning from `useVirtual()` and when I used that, everything resized properly in all my testing. My one concern about this is that this does not seem to be documentation so is this a safe method to use and the documentation is just missing or this method is not intended to be used?

**Comment by piecyk** [comment]
Yep, documentation is missing. Also the `measure` is a bit confusing name imho, calling it will reset measured cache, as a side effect virtual items will be re-created with new measureRef and that will read new measurements. 

This use case looks like ideal for `ResizeObserver` api, was wondering a bit how we can warp useVirtual with it and keeping the api simple without custom item components.

Maybe something like this

```js
const useVirtualResizeObserver = options => {
  const measureRefCacheRef = React.useRef({});
  const elCacheRef = React.useRef({});

  const roRef = React.useRef(
    new ResizeObserver(entries => {
      entries.forEach(entry => {
        const el = entry.target;
        const index = el.getAttribute("data-index");
        measureRefCacheRef.current[index](el);
      });
    })
  );

  React.useEffect(() => {
    const ro = roRef.current;
    return () => {
      ro.disconnect();
    };
  }, []);

  const rowVirtualizer = useVirtual(options);

  const refs = React.useMemo(() => {
    const obj = {};
    for (let i = 0; i < options.size; i++) {
      obj[i] = el => {
        if (el) {
          // sync
          measureRefCacheRef.current[i](el);

          el.setAttribute("data-index", i);
          roRef.current.observe(el);
        } else if (elCacheRef.current[i]) {
          roRef.current.unobserve(elCacheRef.current[i]);
        }
        elCacheRef.current[i] = el;
      };
    }
    return obj;
  }, [options.size]);

  for (let i = 0; i < rowVirtualizer.virtualItems.length; i++) {
    const item = rowVirtualizer.virtualItems[i];
    if (item.measureRef !== refs[item.index]) {
      measureRefCacheRef.current[item.index] = item.measureRef;
    }
    item.measureRef = refs[item.index];
  }

  return rowVirtualizer;
};

// and use it like useVirtual

const rowVirtualizer = useVirtualResizeObserver({
  size: rows.length,
  parentRef
});
```

ResizeObserver will detect changes to element and call measureRef to get new measurements

**Comment by rzec-pki** [comment]
I am using `ResizeObserver()` (though my implementation is a bit simpler but it does what I need) but thanks for the more detailed example (might be useful in the future) and that `useVirtual().measure()` is fine to use and the documentation is just missing.

**Comment by piecyk** [comment]
Yeah, complexity comes from that this implementation keeps the measureRef stale between re-renders.

So react will not call it twice during updates https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs basic not reading offsetWidth / offsetHeight from element to compare new size to cached one, that could be perf win while scrolling, 

> and that useVirtual().measure() is fine to use and the documentation is just missing.

It's fine, just good to know the implication, that when calling measure() that sizes are lost and the whole cache need to be re-builded. For example scrolling to middle of list and calling measure() will most likely break what items are rendered.
