### ISSUE TITLE
Animation: Transition property causes strange behaviour 

### ISSUE THREAD

**Issue by Karpengold** [tannerlinsley/react-virtual#171]
https://codesandbox.io/s/practical-breeze-f9p6g?file=/src/index.js

I'm trying to implement list with expanding/collapsing logic and animation for it, I added transition property to each virtual item and it seems it brokes some internal logic and list shows strange behaviour. If I remove transition property everything works perfect 
For some reason first click on row doesn't cause items offsets recalculation if transition prop is provided, only second rerender does it.

**Comment by piecyk** [comment]
> For some reason first click on row doesn't cause items offsets recalculation if transition prop is provided, only second rerender does it.

It's because react-virtual don't observe resizing of element out of box, that's why you see changes in second re-render. One option here is to use ResizeObserver, something like https://codesandbox.io/s/react-virtual-resizeobserver-transition-z9lxd

**Comment by Karpengold** [comment]
@piecyk Thank you for the working example. I need to check if I can combine it with my current realization: I don't know exact height of the item in expanded state and I use react-resize-detector (which uses ResizeObserver) to get the height for each item after mounting and set it to the state. 
Anyway I think it can be closed, thanks

**Comment by piecyk** [comment]
>  I don't know exact height of the item in expanded state and I use react-resize-detector (which uses ResizeObserver) to get the height for each item after mounting and set it to the state.

Exactly that's the point of ResizeObserver, to detect the height as it's unknown. In above codesandbox height is provided for simplicity of the example, also you don't need to store it on state as it will be stored in react-virtual.

**Comment by piecyk** [comment]
Height is stored on virtualItems. 

>  to show placeholders with correct height during scrolling. 

Here when you are talking about correct height, is the height of component when not scrolling. Basic you don't want loose already know heights. If you could provide codesandbox example that would help.

**Comment by Karpengold** [comment]
@piecyk It was my fault, I totally forgot that virtualRow contains size attribute and tried to store expanded height independently. Sorry and thank you :)

**Comment by piecyk** [comment]
@Karpengold yep, it's know issue #112 basic visible range is only calculated on scroll that's why there is empty space after collapse till scroll happens. 

There is a PR to fix the issue https://github.com/tannerlinsley/react-virtual/pull/166

**Comment by Karpengold** [comment]
Ok thank you!
I assume this issue could be also related to the same topic (or it is expected behavior?): 
If I expand partially visible item expanding appears to the top 

https://user-images.githubusercontent.com/17138959/128250991-9b440939-cce1-4998-8a47-0a8dac2a7130.mov

**Comment by piecyk** [comment]
> Ok thank you!
> I assume this issue could be also related to the same topic (or it is expected behavior?):
> If I expand partially visible item expanding appears to the top
> 
>  2021-08-04.23.32.56.mov

No, not connected, it's expected but imho not desired. 

Basically if size of element changed in items above the scroll offset, we will try to compensate it by manually calling scroll to reduce the list jumping. https://github.com/tannerlinsley/react-virtual/blob/master/src/index.js#L158-L160

I think this should only happen when user is scrolling 🤔 maybe current workaround for your use case would be to call scrollToIndex before expanding the item.

**Comment by Karpengold** [comment]
@piecyk unfortunately this functionality triggers scroll event (cause if item start is less than offset react-virtual call scrollTo event) and in my case if I expand partially visible row all items replaces by their placeholders by a moment.. It would be nice if I can avoid triggering scrolling on expand somehow

**Comment by piecyk** [comment]
>  It would be nice if I can avoid triggering scrolling on expand somehow

You can do it, by custom logic in `scrollOffsetFn` with some predicate to check if animation is pending, something like https://codesandbox.io/s/react-virtual-resizeobserver-transition-forked-wtrfk

**Comment by Karpengold** [comment]
@piecyk I'm just wondering maybe it would be better to look if `item.end` instead of `item.start` is out of the visible box and in this case do scroll to prevent list of jumping? In this case this hacks in case of animation could be avoided (actually for some reason our last example doesn't work for my case :D)

**Comment by piecyk** [comment]
> I'm just wondering maybe it would be better to look if item.end instead of item.start is out of the visible box and in this case do scroll to prevent list of jumping? 

@Karpengold it will now work, as we need `item.start` to adjust the scroll also for partial visible items.

> actually for some reason your last example doesn't work for my case :D

Why?

**Comment by Karpengold** [comment]
@piecyk I'm not sure why this example doesn't work for my case, but there are also some issues anyway, firstly some strange behavior after collapsing partially visible items: 

https://user-images.githubusercontent.com/17138959/128998392-2daf9ead-3157-48c3-8c37-3e356d4b9300.mov

Also in this case of expending partially visible items triggers scroll event of list component, and placeholders appear instead of real items, but for user no scroll event is visible and placeholders aren't supposed to be here

**Comment by Karpengold** [comment]
@piecyk what do you think, is there an another way to avoid this behavior in case of partially visible items?

**Comment by piecyk** [comment]
@Karpengold hard to say, don't seeing any easy solution. Adjusting scroll position when scrolling backward is crucial to limit jumping. Maybe extending the scrollToFn with reason then you could prevent this scroll when there is pending animation, but this would need big of refactoring of internals 🤷‍♂️ 

```js
let pendingAnimation = false
scrollToFn(offset, reason) {
  if (reason === 'ItemSizeChange' && pendingAnimation) {
    pendingAnimation = false
    return
  }
} 

// set pendingAnimation to true, when animation will start 
```

**Comment by Karpengold** [comment]
@piecyk but this issue is not only about animation actually, it is about any height changes of partially visible items - if it appears, react-virtual tries to compensate it by scrolling the list.

**Comment by Karpengold** [comment]
As example: https://codesandbox.io/s/react-virtual-resizeobserver-transition-forked-h7mom?file=/src/App.js

**Comment by piecyk** [comment]
> @piecyk but this issue is not only about animation actually, it is about any height changes of partially visible items - if it appears, react-virtual tries to compensate it by scrolling the list.

Yes that is true. Maybe we should only adjust the scroll position while scrolling backward 🤔

**Comment by Karpengold** [comment]
@piecyk maybe this adjusting could be provided as a parameter function? Something like param to be set by user

```
const { adjustSize } = options;
...
if (item.start < scrollOffset) {
        adjustSize ? adjustSize(item, scrollOffset, measuredSize) : defaultScrollToFn(scrollOffset + (measuredSize - item.size));
}
```
