### ISSUE TITLE
The "Dynamic Rows/Cols/Grid" demo is broken

### ISSUE THREAD

**Issue by afterwind-io** [tannerlinsley/react-virtual#21]
The compiler is complaining about missing "estimateSize" in the options.
https://codesandbox.io/s/github/tannerlinsley/react-virtual/tree/master/examples/dynamic

Anyway it is a great project.  Keep up the good work!

**Comment by tannerlinsley** [comment]
It’s a code sandbox caching issue. Hit the refresh button next to the react-virtual dependency.
