### ISSUE TITLE
SSR support?

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/react-virtual#218]
Hi @tannerlinsley 👋 

Hoping to put together an example of using Remix with React Virtual for infinite scroll and I noticed that on the server render the `rowVirtualizer.virtualItems` only has two items. I know you can't really measure things on the server, but could I pass the height (or an estimated height) of my `parentRef` so you can server render the (estimated) correct number of virtual items?

**Comment by tannerlinsley** [comment]
I think that’s more than reasonable to ask for :) I’ll see what I can do.

**Comment by piecyk** [comment]
@kentcdodds i think you could use `useObserver` for setting height/width, like 

```tsx
const rowVirtualizer = useVirtual({
  size,
  parentRef,
  useObserver: React.useCallback(() => ({ height: 400, width: 400 }), []),
})
```

But there is a bug when parentRef is null as we reset visible range https://github.com/tannerlinsley/react-virtual/blob/master/src/index.js#L133

IMHO better is to move to calculate range on every render via #217

**Comment by kentcdodds** [comment]
> IMHO better is to move to calculate range on every render via #217

That's fine with me (I don't care one way or the other). I just need the server render to have close to the right number of items rendered.

**Comment by tannerlinsley** [comment]
[This PR](#217) (just merged) should give you what you need with `initialRect`

**Comment by kentcdodds** [comment]
Super duper. Thanks!
