### ISSUE TITLE
Cannot get correct scroll on last item

### ISSUE THREAD

**Issue by silviuaavram** [tannerlinsley/react-virtual#22]
Hi! I picked up Kent's work on `useCombobox` and `react-virtual` and came up with this: https://codesandbox.io/s/epic-morse-jffe1.

Released an alpha for Downshift to fix some things, and now it should work, apart from this use case: highlighting from first item to last (using ArrowUp) is not bringing the item into view. Scroll somehow fails (unless I pass `{align: 'start'}` to the scroll function. However I don't want to do that for all cases.

Last item is scrolled correctly when moving from second to last to last (using ArrowDown).

Any idea why I get this bad scroll in the use case above? Thanks!

**Comment by tannerlinsley** [comment]
Looks like a bug I'll find a fix in the morning 👍

**Comment by silviuaavram** [comment]
Also looked into it a bit more. It seems that, with the example above, on arrow up from the first item, react-virtual returns `virtualItems` but without the last one. useCombobox will have highlightedIndex as 25, but last item from react-virtual comes as 24.

Not sure if it's a react-virtual bug or the example bug. Hope this helps in fixing it. If this will get fixed then the useCombobox - react-virtual combination should work (y)

**Comment by tannerlinsley** [comment]
Just pushed a fix for this. And better yet, it fixes some other edge cases with dynamic virtualization as well. Update your sandbox dep and you should be good to go :)

**Comment by kentcdodds** [comment]
This almost does it: https://codesandbox.io/s/reverent-goldwasser-g6muv

Hit up and it does scroll down, but not far enough.

**Comment by kentcdodds** [comment]
Updated it to use `onStateChange` rather than `stateReducer` (because the user-provided state reducer *should* be pure): https://codesandbox.io/s/dreamy-gareth-yeyxq

However, same issue.

**Comment by silviuaavram** [comment]
Did you get @tannerlinsley fix? I see it's still 2.1.8, update to 2.1.9.

**Comment by kentcdodds** [comment]
Oh duh! Nice. Thanks both of you 🎉 Looks like it's working like a charm :)

**Comment by kentcdodds** [comment]
Weird thing happened. I had the menu open, then I changed tabs to send that comment, and when I went back, I saw this:

![image](https://user-images.githubusercontent.com/1500684/81724112-112a6e80-9441-11ea-8156-0f7824a103da.png)

Any ideas?

**Comment by kentcdodds** [comment]
Figured it out. I think it's a bug in downshift. But if you make it so there's no items left (type gibberish) and then arrow down, there's a "highlightedIndex" change which triggers me to call `scrollToIndex` to `0`, but there's no item at index 0 because there are no items.

I think the solution would be in downshift to not update the highlighted index to an index that doesn't have an associated item.

**Comment by tannerlinsley** [comment]
Yeah, I had a safeguard against this to just return early in RV, but I think this is an error you'll want to see if you're trying to scroll to an index that doesn't exist.

**Comment by silviuaavram** [comment]
I think the problem is right inside the method calculating the next highlighted index, I also need to check if items.length is 0. Will fix and write a test in the PR already opened.

nit: you can use `onHighlightedIndexChange` @kentcdodds so you don't have to perform that check inside the onStateChange.
