### ISSUE TITLE
How we can implement multiple virtual list which is using window scroll?.

### ISSUE THREAD

**Issue by bipinrajbhar** [tannerlinsley/react-virtual#228]
### Discussed in https://github.com/tannerlinsley/react-virtual/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **bipinrajbhar-rh** December  4, 2021</sup>
How we can implement multiple virtual list which is using window scroll?.

https://github.com/bvaughn/react-virtualized/issues/1324#issuecomment-477683188

@petersendidit , @piecyk , @mogelbrod , @oskarhane , @shastri9999.
</div>

**Comment by cannap** [comment]
hi i know this is an old question but is this possible?

**Comment by piecyk** [comment]
Yes, by having multi `useWindowVirtualizer` instances just each virtualizer need to have proper scrollMargin that informs where the list starts, for example

```
header - size 10
list1 - size 500 // scrollMargin = 10
list2 - size 500 // scrollMargin = 500
```
