### ISSUE TITLE
Dynamic measurement not working

### ISSUE THREAD

**Issue by Andrey-Bazhanov** [tannerlinsley/react-virtual#23]
First of all thanks for great lib. I'm big fan of your OSS projects!

`measureRef` do noting in current implementation. If we looking into official [example](https://codesandbox.io/s/github/tannerlinsley/react-virtual/tree/master/examples/dynamic) we can see that height of row came from hardcoded array value (`${rows[virtualRow.index]}px`) this behaviour isn't look like "dynamic measurement"

**Comment by tannerlinsley** [comment]
measureRef measures the *resulting* dimensions of the element, then adjusts the *position* of it and all other elements based on that measurement. The actual width or height of the element are not (and shouldn't be) dictated by react virtual, otherwise it wouldn't be dynamic at all.

Here is a better example where the dimensions are "naturally" produced by the content of the row: https://codesandbox.io/s/determined-beaver-vi2rf?file=/src/index.js

**Comment by Andrey-Bazhanov** [comment]
Awesome! Thanks for clarification.

Maybe we should update example for more cleaner understanding?

For example generate random length of words using faker. 

If you agree, I can create pull request

**Comment by tannerlinsley** [comment]
Sure! I'd be fine with that. Make sure it works for all 3 of the dynamic types (row/col/grid)

**Comment by lizy0329** [comment]
> measureRef measures the _resulting_ dimensions of the element, then adjusts the _position_ of it and all other elements based on that measurement. The actual width or height of the element are not (and shouldn't be) dictated by react virtual, otherwise it wouldn't be dynamic at all.
> 
> Here is a better example where the dimensions are "naturally" produced by the content of the row: https://codesandbox.io/s/determined-beaver-vi2rf?file=/src/index.js

Can the url of the example be replaced with this? I am also very confused when looking at the old examples

**Comment by yuri-scarbaci-lenio** [comment]
This is not documented either right?
![image](https://user-images.githubusercontent.com/59743524/97190869-8ea32a80-17a6-11eb-9d6d-e565d7a891b6.png)

the current readme.md clearly states that estimateSize is ***required*** and the sandbox you shared shows an implementation that doesn't require it...

Which is the latest state of this? is it required or not?

**Comment by kimroen** [comment]
> the current readme.md clearly states that estimateSize is _**required**_ and the sandbox you shared shows an implementation that doesn't require it...
> 
> Which is the latest state of this? is it required or not?

It is required, it's used when estimating the full height of the scrollable content and the positions of each item. It's used when the item hasn't been rendered yet (or might have changed).

**Comment by yuri-scarbaci-lenio** [comment]
@kimroen  could you please clarify?

In the project we are working on we are not passing any value there and it works...
 and as per the related code-sandbox you can see it "works" without it,
 
 when you say it's required you mean that "strange behaviour may be observed if not provided" ?
 
 I will investigate a bit on my own to check what the "default" value would be when not provided, just to understand why everything works even when not provided I guess

**Comment by yuri-scarbaci-lenio** [comment]
For anyone coming here from google
 in version 2 of this library
 
`estimateSize` is indeed "optional" because the code is actually providing a default estimate size
as per https://github.com/TanStack/virtual/blob/main/src/index.js#L5

not only it's optional by implementation,
  the test suite is not providing any `estimateSize` parameter,
    as in, the test run by the library actually certifie that the library do work when estimateSize is not provided
    
as per
   https://github.com/TanStack/virtual/blob/main/src/tests/index.test.js#L17
   
Also, 
  I'm still trying to understand why, 
     but actually
  passing `estimateSize` function (even the same default one) in some case may have different final result than not passing it...

**Comment by piecyk** [comment]
Hi, estimateSize is used for initial calculation as @kimroen wrote above. For example if your rows are an average of 150px, having 100 rows will estimate that the list is 15000px height. Keeping the default function ( specially not documented ) was a mistake.

**Comment by yuri-scarbaci-lenio** [comment]
What about the test suite?
  the test suite is ONLY testing with the default estimateSize...
  also I am having huge troubles testing with jest, my understanding is that for the test to work in jest `useObserver` and 
  ```
   const onRef = (virtualRow) => (el) => {
      if (el) {
        jest.spyOn(el, 'offsetHeight', 'get').mockImplementation(() => 25);
      }
      virtualRow.measureRef(el);
    };
    ```
    must be mocked up, problem is, when  I try to do integration testing I can't really customize the `measureRef`, I can at most mock up `useObserver`...
    I will investigate further to see If I can come up with a smart way to mock it up in integration testing...
    
    meanwhile I would like some insight (version 2) regarding this:
I'm having an issue where using estimateSize && having the items set the `height: ${size}px` result in the rows to have a fixed `height` the same as the one from the estimateSize function...

Am I supposed to use `minHeight` instead? what is the expected API for having estimateSize work without impacting the actual size of the rows?

**Comment by piecyk** [comment]
> What about the test suite?

Test use default estimateSize that returns 50px, no providing it was a mistake and we should use explicit estimateSize. Don't follow what are you after? Basic you need to check what height your rows are, and guess closest number.

> also I am having huge troubles testing with jest, my understanding is that for the test to work in jest useObserver and

you can also provide your own https://github.com/TanStack/virtual/blob/main/src/index.js#L9-L13 that will return size. 

Overall would recommend upgrade to beta, we are pretty close to stable release.

**Comment by yuri-scarbaci-lenio** [comment]
What I'm trying to accomplish is this:
first render:
![image](https://user-images.githubusercontent.com/59743524/210840747-9591b8a3-6c21-432e-8657-f833351e0a2a.png)
 first rows "height" is 70
 
 something happens, the height changes 
 
![image](https://user-images.githubusercontent.com/59743524/210840876-e00dafc6-dae2-4e0c-b632-833ff8f77d2a.png)

A new element is added
![image](https://user-images.githubusercontent.com/59743524/210841008-e6be490f-0a8d-497e-858c-bae720c18803.png)

the new item height should NOT be the "maximum" height detected so far, it should be the item actual height itself

so basically this:

![image](https://user-images.githubusercontent.com/59743524/210841808-27b87c7f-c094-4fdd-a536-02e336b946fb.png)

I can achieve this with the following code:
```
{virtualItems.map((virtualItem) => {
          const { index, measureRef, start } = virtualItem;
          return (
            <div
              ref={measureRef}
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                transform: `translateY(${start}px)`,
              }}
              role="listitem"
              key={`ds-virtual-list-item-${uid(6)}`}
            >
              {filteredChildren[index]}
            </div>
          );
        })}
```
as you can see, i'm not using `size` in my items, i'm completely ignoring them, but i'm not sure if this is expceted by the library or if it's required for me to somehow use the `size` provided by each virtual item...


I want to move to the beta ASAP,
That's the reason I'm creating integration tests,
I need to make sure that I don't have breaking changes in my component, the final behavior to the end user of my component should be the same even if I internally use beta... I need to be sure this is true, hence why the testing...

**Comment by piecyk** [comment]
Yes, in dynamic mode the size should not be used in styles, the example was misleading to use it, overall the idea behind it was to simulate different heights, but instead of faker should be used.

**Comment by yuri-scarbaci-lenio** [comment]
Thank you for the library and for clarifying all of this!

**Comment by yuri-scarbaci-lenio** [comment]
Last thing, regarding unit testing

```

import * as virtualLib from 'react-virtual';

...

describe('Should be virtualized', () => {
  afterAll(() => {
    cleanup();
  });

  test('Should renders 24 rows with a total height of 900px and 100px per item, overscan 15', async () => {
    const itemHeight = 100;
    const height = 900;
    const width = 400;
    
    const originalUseVirtual = virtualLib.useVirtual;
    virtualLib.useVirtual = jest.fn((virtualOpts) =>
      originalUseVirtual({
        ...virtualOpts,
        useObserver: () => ({ height, width }),
        measureSize: () => itemHeight,
      }),
    );
    render(<AComponentThatInternallyUsesUseVirtual  />);
    virtualLib.useVirtual = originalUseVirtual;
    
    await screen.findByText('Test 1');
    expect(screen.getByText('Test 1')).toBeInTheDocument();
    expect(screen.getByText('Test 15')).toBeInTheDocument();
    expect(screen.getByText('Test 24')).toBeInTheDocument();
    expect(screen.queryByText('Test 25')).not.toBeInTheDocument();
    expect(screen.queryByText('Test 34')).not.toBeInTheDocument();
  });
});
```

do you think this way of unit-testing is fine?

Basically I am creating an higher order functions that forces the `useObserver` and `measureSize` only during jest execution, by mocking the method from useVirtual...

This is working in my case (with react-virtual v2)
  I think this is extremely read-able, so maybe we could have the test-suite do something like this and double-up as the "expected way" to integration test component using react-virtual?
 (I'm mocking it inside the test-case itself for being able to customize the parent height, item height and width on a per-test cases, of course something more global could also be done if such micro-control is not required)
 
  Thoughts on this?
  @piecyk
