### ISSUE TITLE
onScrollElement removed in 2.10.0

### ISSUE THREAD

**Issue by Dm1Korneev** [tannerlinsley/react-virtual#233]
Hello

Why `onScrollElement` was removed in 2.10.0?
It could cause unexpected errors
Looks like it should be breaking release.

**Comment by piecyk** [comment]
Yes it should be a major release, i'm sorry for that, it was a mistake. @tannerlinsley can we sort this out?

**Comment by henrikq** [comment]
First and foremost, thanks for a great library. I really love it.

That said, the removal of `scrollOffsetFn` is a breaking change to me. I considered creating a new issue, but opted to just comment here.

I'm sure https://github.com/tannerlinsley/react-virtual/pull/219 was a step in the right direction, but its not clear to me how to migrate to v2.10.0 given that i need need to manipulate the offset due a sticky header.

**Comment by tannerlinsley** [comment]
We've finally reverted all of the changes on master and pushed a new patch release. Breaking changes have been moved to the `next` branch. Stay tuned for the next major version!
