### ISSUE TITLE
SSR support for windowRef

### ISSUE THREAD

**Issue by thanhlmm** [tannerlinsley/react-virtual#234]
![image](https://user-images.githubusercontent.com/9281080/147225153-ab369369-e313-4390-b923-f0d141f1c75e.png)
I got this error when using windowRef on Nextjs

**Comment by piecyk** [comment]
> I got this error when using windowRef on Nextjs

It's expected as window is not defined, basic you need to check if it does

```ts
const windowRef = React.useRef(typeof window !== 'undefined' ? window : null)
```

Also when doing SSR, add initialRect = { width: number, height: number } that will used for calculating visible range on server.

**Comment by thanhlmm** [comment]
@piecyk got it. Thanks!
