### ISSUE TITLE
rowVirtual.totalSize is change when scrolling.

### ISSUE THREAD

**Issue by hoahiep506** [tannerlinsley/react-virtual#243]
I founded a issue with this case https://codesandbox.io/s/resizeobserver-react-virtual-6131c?file=/src/index.js 
U see the `rowVirtual.totalSize` is change when we scroll and make the cursor move out scroll bar, I think this is a bug.

How can we fixed this ?

**Comment by piecyk** [comment]
That is correct, in dynamic size list we don't know exact size of elements before we render them, totalSize is calculated with real sizes + estimate sizes. That's why when we scroll totalSize is changing.

**Comment by tannerlinsley** [comment]
Yep, totalSize is a calculated value based on what we know at any given moment about the items in the list. Expect it to change unless you are using static/variable sizes that will not change per item.
