### ISSUE TITLE
"Maximum update depth exceeded." for a virtualized view that appears late

### ISSUE THREAD

**Issue by tmcw** [tannerlinsley/react-virtual#245]
Unfortunately I haven't been able to create a reduced test case for this, despite really putting some effort in - so close if irrelevant.

I have a scrollable element that appears after a state change in the application. In react-virtual 2.10, its appearance triggers an update loop with this set state:

https://github.com/tannerlinsley/react-virtual/blob/76ba050eadd7a0bacefe86fba2e490349cfc6257/src/index.js#L38-L40

I don't know how the above code should work, ideally - all of the other examples of a `setElement` in an isomorphic update effect hook check that the effect will make a change:

https://github.com/tannerlinsley/react-virtual/blob/76ba050eadd7a0bacefe86fba2e490349cfc6257/src/useRect.js#L13-L17

My expectation, then, is that the first example will cause an update loop, as it does in my application. Downgrading to 2.9.0 avoids this issue, because it doesn't have the same useElementScroll abstraction.

**Comment by tannerlinsley** [comment]
We've recently reverted a breaking change on master and pushed a new patch release. Breaking changes have been moved to the `next` branch. Will you please confirm this is still an issue?
