### ISSUE TITLE
Rename `items` to `virtualRows`

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/react-virtual#3]
What *I* am rendering I call "items" what *you* have given me is a "virtualRow". So `rowVirtualizer.virtualRows` seems to make more sense to me.

**Comment by tannerlinsley** [comment]
How about `virtualItems`

**Comment by kentcdodds** [comment]
Ah, yeah, I guess it's not just rows, but could be columns.

Yeah, I like `virtualItems` better 👍

**Comment by tannerlinsley** [comment]
Sounds good!

**Comment by tannerlinsley** [comment]
Done in 2.0.0 🎉
