### ISSUE TITLE
How is it different from react-window/react-virtualized?

### ISSUE THREAD

**Issue by diegohaz** [tannerlinsley/react-virtual#4]
Hi, @tannerlinsley! Thanks for the amazing work here!

As a maintainer, I know that this kind of question is a little bit annoying. But, as a user of alternative libraries like react-window, it feels like knowing how it compares to the available alternatives, beyond the hook API, is the easiest way to understand the library.

So, my suggestion is to add a section in the README about this.

**Comment by tannerlinsley** [comment]
I've added a section to the README. Thanks!

**Comment by AgarwalPragy** [comment]
Has this section been removed from the README? I can't seem to find it in the docs either.

**Comment by tregoning** [comment]
This is the Readme on the date of that comment, I am assuming he is referring to the "WHY" section

Link: https://github.com/TanStack/virtual/tree/70779a2b129867d2a7a304adbb6ff1d5e26e7203#why
