### ISSUE TITLE
Change in height of parent div, not re-renders complete view-port list

### ISSUE THREAD

**Issue by kartikag01** [tannerlinsley/react-virtual#63]
@tannerlinsley  
Thanks for this great library,
I was upgrading `react-window` with `react-virtual` and encountered an issue 

https://codesandbox.io/s/hopeful-bassi-fxbdk?file=/src/index.js

When I controlling the height of parent ref div based on item rendering, then dynamically changing the item count, then rerending is not happening properly.
Check on the above code sandbox link, click on the button then we to scroll a bit to refresh the list.

![image](https://user-images.githubusercontent.com/10574227/93073119-0ce8b900-f6a0-11ea-91e4-1d9bfe9c5a07.png)
![image](https://user-images.githubusercontent.com/10574227/93073140-16722100-f6a0-11ea-9ed4-97489d1a7af3.png)

**Comment by potty** [comment]
I have the same issue. When the list is first rendered, it will only display 4 out of 100 items, when I scroll a little bit, items are displayed.

**Comment by ConneXNL** [comment]
I think my issue is actually the same problem at https://github.com/tannerlinsley/react-virtual/issues/69
