### ISSUE TITLE
Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by ghengeveld** [tannerlinsley/react-virtual#64]
Oftentimes, parentRef will have value `undefined` at first render. This breaks with `TypeError: Cannot read property 'scrollTop' of undefined` in react-virtual 2.2.4 and above. It works fine in 2.2.3.

See for example: https://codesandbox.io/s/trusting-shamir-05gpx
Changing to react-virtual 2.2.3 fixes it.

**Comment by kentcdodds** [comment]
I think I've seen this as well. This is the change: https://github.com/tannerlinsley/react-virtual/compare/v2.2.3...v2.2.4

Specifically, this is the line that's causing the issue: https://github.com/tannerlinsley/react-virtual/compare/v2.2.3...v2.2.4#diff-1fdf421c05c1140f6d71444ea2b27638R74

**Comment by kentcdodds** [comment]
Made a PR to help out a bit.

**Comment by ghengeveld** [comment]
I'm running into a new issue now :(
`Cannot read property 'addEventListener' of undefined`
See https://codesandbox.io/s/storybook-search-virtualized-jyq1u?file=/src/Tree.js (change to react-virtual 2.2.6)

**Comment by kentcdodds** [comment]
We should probably add a test for this use case 😅
