### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by InstinctSolutions** [tannerlinsley/react-virtual#68]
`
    const rowVirtualizer = useVirtual({
        size: pokeData ? pokeData.pokemon_entries.length: 0,
        parentRef,
        estimateSize: useCallback(() => {
               return pokeData ? pokeData.pokemon_entries.length: 0
        }, []);,
        overscan: 12
    });
`
<img width="728" alt="Screenshot 2020-09-26 at 8 30 46 AM" src="https://user-images.githubusercontent.com/59808781/94325831-f6f9c300-ffd2-11ea-8e66-a2b6577d7321.png">

may I know what is the reason, I developed this in react typescript

**Comment by kidroca** [comment]
There seems to be a bug in the latest releases I'm using `"react-virtual": "=2.1.10"` where I don't get this error
