### ISSUE TITLE
How to NOT re-render list rows when scrolling?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [tannerlinsley/react-virtual#74]
Assume I have the following settings:

The container height:  400
The row height: 40

```
const virtual = useVirtual({
  size: 1000,
  parentRef,
  overscan: 20,
  estimateSize: useCallback(() => 40, [size]),
})
```

It seems that the container re-renders every visible row every time new row appears. This behavior maybe intentional but what if my row is heavyweight and the cost to re-render them is not trivial?

What I want to do is re-render only when the last row is visible.

In the above setup, I should see re-render happen once when i scroll to the 30th element, and insert next 20 element since overscan is 20.

---

Edit:

After play around with the source code, I see that `setRange(prevRange => calculateRange(latestRef.current, prevRange))` actually cause the re-render every time index change.

I changed the if condition from 
```
  if (!prevRange || prevRange.start !== start || prevRange.end !== end) {
    return {
      start: start,
      end: end
    };
  }
```

to 

```

  if (!prevRange ||
    Math.abs(start - prevRange.start) > overscan - 1 ||
    Math.abs(end - prevRange.end) > overscan - 1
    ) {
    return {
      start: start,
      end: end
    };
  }
```

It reduce re-render from 999 to 50 when the data size is 1000 and overscan is 20.

Maybe we can allow developer to pass custom `calculateRange` function if they need to optimize performance? or improve `calculateRange` when overscan is used?

https://github.com/tannerlinsley/react-virtual/blob/master/src/index.js#L77

**Comment by mogelbrod** [comment]
I think this could be a nice opt-in behavior to reduce the number of re-renders.
Are your item components memoized though? Items that stay within the window shouldn't be re-rendered (IIRC) if they're memoized (via `React.useMemo` or `React.PureComponent`) and you make sure to key them on the `virtualItems[x].index` property, or something on the item data itself that is immutable.

**Comment by X7Becka** [comment]
Does maintainer watches the issues?

**Comment by tannerlinsley** [comment]
Yep! Just prioritization. I’ll get to this issue soon.

**Comment by piecyk** [comment]
Overall as @mogelbrod suggested this need to be handled by memoizing the row result. For example, extracting row to it's own component and wrapping it with `React.memo`.

**Comment by piecyk** [comment]
Some quick points to consider when things start to be slow 

* as react-virtual is a hook, the whole component will re-render whit it. If it's a complex one, best is to extract it to smaller one.
* memoize the row result
* when row update it's internal state base on mouse actions, for example tooltip etc, one options is to disable the `pointer-events` when scrolling. 

https://codesandbox.io/s/react-virtual-performance-list-pmyo2

**Comment by paulm17** [comment]
I have this same issue:  https://www.loom.com/share/8e28b4db36ab4a6980fb4ca4530b65bc

I have tried to memoized the column item.  But to no effect.

How can I ensure that the images are not retrieved again when scrolling back to an area already seen?

Thanks

**Comment by bestwebdeveloper** [comment]
@paulm17 Depending on how you serve images to a user. I guess there is a url in a src. If yes, then there is only browser caching may help. Another way is to convert images to a Blob on load and use this blob as a source for image instead of url then you will be able at least cache images after retrieving them, but this of cause will occupy more memory of the users.

**Comment by paulm17** [comment]
This is an old issue.  I've actually dropped this lib and using react-window and also using indexDB as browser caching didn't help.

So I consider my solution a solved issue, no need to reply.  😄

**Comment by xiaoyu-tamu** [comment]
I end up use my own version react-virtual, I think this PR #164 also implement it.
