### ISSUE TITLE
Ambiguous API documentation

### ISSUE THREAD

**Issue by ifndefdeadmau5** [tannerlinsley/react-virtual#79]
It seems like the term 'size' is used here as a kind of measurement(px) throughout the documentation, 
but somehow only this **required** option is remained as an exception.

------------------------------
### Options

- `size: Integer`
  - **Required**
  - The size of the virtualizer
-------------------------------

This could be easily misleading to understand this unit as a measurement too, which is wrong.
I think that instead of current description `The size of the virtualizer`, something like `The total count of elements` would be more appropriate.
Please correct me if I'm wrong

**Comment by tannerlinsley** [comment]
Open a PR to improve it 👍

**Comment by ifndefdeadmau5** [comment]
@tannerlinsley thanks, I've created a PR :)
