### ISSUE TITLE
Dynamic height on Internet Explorer 11 causes infinite render

### ISSUE THREAD

**Issue by sarioglu** [tannerlinsley/react-virtual#84]
Hi,
I am trying to use react-virtual on Internet Explorer 11 to render a dynamic-height list. It looks like `getBoundingClientRect` returns high precision floating point numbers as element's height and these measurements somehow slightly change at each render. For example, an element's height is measured as `32.6201171875` at first and `32.619995117` at the second pass. That's why the list updates itself in infinite loop.

Initially I thought I can fix it by using `.toFixed(2)` at `index.js:110` but cannot be sure if it breaks anything.

**Comment by alexmnv** [comment]
Can confirm. IE11 hangs when using dynamic measurement rendering.

**Comment by cascornelissen** [comment]
Running into the same issue, did any of you find a solution to this by any chance?

**Comment by sarioglu** [comment]
Right, having a flexible parent significantly decreases the performance. But it is same for other virtualized list implementations as well.

For the IE related issue, I fixed it by casting sizes to integer before comparing them and it is fine for me since a difference smaller than 1px is not meaningful. But I haven't opened a PR here since I cannot be sure if it causes another issue.

**Comment by piecyk** [comment]
@sarioglu this should be fixed via https://github.com/tannerlinsley/react-virtual/pull/160
