### ISSUE TITLE
measureRef gives wrong size at first render

### ISSUE THREAD

**Issue by sarioglu** [tannerlinsley/react-virtual#85]
Hi,
I am trying to use react-virtual to render a dynamic-height list. When I pass measureRef to my list item wrapper like `<div ref={measureRef}><ListItem /></div>` it calculates the height of each visible list item as `48px`. But this value is not correct. Calculation becomes correct when I start scrolling for the first time to trigger a change on visible portion of the list.

When I pass the ref using a arrow function like `<div ref={element => measureRef(element)}><ListItem /></div>` it calculates and renders correctly.

**Comment by babycourageous** [comment]
@sarioglu - this issue advice saved me. I was having trouble with lists of a certain size not displaying correctly until i scrolled as well. This arrow function fix solved the problem!

**Comment by spirit-team** [comment]
@sarioglu  Thanks for the tip!!

**Comment by luonglearnstocode** [comment]
![image](https://user-images.githubusercontent.com/15094020/105098674-1c936680-5ab3-11eb-921f-fe5f7116ec87.png)
Thank you for this issue. However, typescript complains about this. Any ideas on how to resolve this?

**Comment by sarioglu** [comment]
Honestly, I've just used `// @ts-ignore` thinking that it is only a temporary hack.

**Comment by ifndefdeadmau5** [comment]
@sarioglu Can you explain further about how this does the trick? I found [this](https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs) in the react docs but not quite sure yet

**Comment by piecyk** [comment]
It's a side effect of how react virtual handles dynamic measurement. It's not supporting watching element for changes, so not reading wrong sizes. It's not called when element changes. 

This can be impl via https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver checkout more at #28

There is no trick here, basic how react works in case of refs. If you pass an arrow function, referentially it is different every time. As in docs 

> it will get called twice during updates, first with null and then again with the DOM element.

The whole measuring happening when calling measureRef, if element changes between re-renders using inline we can catch those changes.

**Comment by meotimdihia** [comment]
Shouldn't we document this problem? 
It takes ~5-6 hours for me to find the reason and lucky, I searched this issue.

**Comment by bradley** [comment]
Believe it's `ref={ref => virtualRow.measureElement(ref)}` now.

**Comment by duonghaiphamkite** [comment]
Thank you very much, it works like a charm

**Comment by piecyk** [comment]
> Believe it's `ref={ref => virtualRow.measureElement(ref)}` now.

Let's not use arrow function with ref, just `ref={virtualRow.measureElement}`
